service:
  name: stackjanitor
app: stackjanitor
#tenant: your-tenant-name

# Add the serverless-webpack plugin
plugins:
  - serverless-webpack

provider:
  name: aws
  runtime: nodejs10.x

functions:
  index:
    handler: src/handler.index
    events:
      - http:
          method: get
          path: index
