name: Release

on:
  push:
    paths:
      - '!.md'
    branches:
      - 'master'

jobs:
  Release:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v1
    - uses: actions/setup-node@v1
      with:
        node-version: '10.x'
    - run: yarn
    - name: Release 🎉
      run:  |
        git checkout master
        git remote rm origin
        git remote add origin https://$GITHUB_ACTOR:$GITHUB_TOKEN@github.com/$GITHUB_REPOSITORY.git
        git fetch
        git config --global user.email octobot@github.com
        git config --global user.name GitHub Actions
        yarn release
      env:
        GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
    - name: DataDog Event Trigger
      uses: jordan-simonovski/datadog-event-action@1.0.0
      env:
        DATADOG_API_KEY: ${{ secrets.DD_API_KEY }}
        EVENT_TITLE: "StackJanitor Release Succeeded! 🎉"
        EVENT_TEXT: Release can be found here: https://github.com/lendi-au/StackJanitor/releases
        EVENT_TAGS: "['app:StackJanitor']"
